# Generated by Django 5.1.7 on 2025-04-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_backend', '0002_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationservice',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_services', to='add_backend.application'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(),
        ),
    ]
