# Generated by Django 5.1.7 on 2025-05-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_backend', '0002_alter_application_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
