version: '3.8'
services:
  db:
    container_name: ConnectProvider-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: conprov
      POSTGRES_DB: ConnectProvider-db
    ports:
      - "5432:5432"