concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Dok"
  url = "http://localhost"
  id = 1
  token = "glrt-bzoxCnA6MQp0OjMKdToxWiAi-336_xb-YO_bHBVeyRA.171btigdr"
  token_obtained_at = 2025-04-29T06:05:04Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
